language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
install:
#  - npm install phantomjs-prebuilt -g
  - npm install -g mocha-phantomjs
  - npm install mocha
  - npm install chai
  - npm install chai-as-promised
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
script:
  - mocha-phantomjs test/testRunner.html
